language: python
# install prerequisites
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install openbabel
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
# run tests
jobs:
  include:
    - stage: test
      python: '2.7'
      script:
        - python -m pytest -v --cov=./isoenum
    - stage: test
      python: '3.4'
      script:
        - python -m pytest -v --cov=./isoenum
    - stage: test
      python: '3.5'
      script:
        - python -m pytest -v --cov=./isoenum
    - stage: test
      python: '3.6'
      script:
        - python -m pytest -v --cov=./isoenum
    - stage: test
      dist: bionic
      python: '3.7'
      script:
        - python -m pytest -v --cov=./isoenum
# generate code coverage report
after_success:
  - codecov
