language: python
# install prerequisites
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install cmake -y
  - wget https://github.com/openbabel/openbabel/archive/openbabel-2-4-1.zip
  - unzip openbabel-2-4-1.zip
  - cd openbabel-openbabel-2-4-1
  - mkdir build && cd build
  - cmake ..
  - make -j2
  - sudo make install
  - cd ../../
  - rm -rf openbabel-openbabel-2-4-1
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
# run tests
jobs:
  include:
    - stage: test
      dist: bionic
      python: '2.7'
      script:
        - python -m pytest -v --cov=./isoenum
    - stage: test
      dist: xenial
      python: '3.4'
      script:
        - python -m pytest -v --cov=./isoenum
    - stage: test
      dist: xenial
      python: '3.5'
      script:
        - python -m pytest -v --cov=./isoenum
    - stage: test
      dist: bionic
      python: '3.6'
      script:
        - python -m pytest -v --cov=./isoenum
    - stage: test
      dist: bionic
      python: '3.7'
      script:
        - python -m pytest -v --cov=./isoenum
# generate code coverage report
after_success:
  - codecov
